name: Release

on:
  push:
    branches: [ main ]
    tags: [ '*' ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Install JDK
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 20

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Assemble for release
        run: ./gradlew assembleRelease --stacktrace --no-configuration-cache
      - name: Publish
        run: ./gradlew publish --stacktrace --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_personalSonatypeIssuesUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_personalSonatypeIssuesPassword }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_personalGpgKey }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_personalGpgPassword }}
